name: CI/CD Pipeline for HTML and CSS Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate HTML and CSS files (optional)
        run: |
          # Install HTML and CSS validators (optional)
          sudo apt-get install -y tidy
          tidy -e index.html
          # You can add more files to validate, like CSS files, etc.

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: success()
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages (or custom server)
        run: |
          echo "Deploying to GitHub Pages or custom server"
          # For GitHub Pages, you can use the following command to push the files
